[profile.default]
src = "src"
out = "out"
solc_version = "0.8.20"
libs = ["lib"]
remappings = ['@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/', 
              '@openzeppelin/contracts=lib/openzeppelin-contracts/contracts',
              '@openzeppelin/contracts-upgradeable=lib/openzeppelin-contracts-upgradeable/contracts',
              '@prb-math/contracts=lib/prb-math/src',
              '@solmate/src=lib/solmate/src']


[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = {key = "${ETHERSCAN_API_KEY}"}

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"

[invariant]
runs = 128
depth = 128
fail_on_revert = true

fs_permissions = [{ access = "read", path = "."}]

# IMPORTANT: should be false in production.
ffi = true